### PR TITLE
Updating firebase-core 11.2.0 to 16.0.1

### PR DESCRIPTION
**Pull request by ldemay**
https://firebase.google.com/support/release-notes/android

### CODE REVIEW

**Comment by TeresaNesteby** [comment]
@segment-integrations/destinations

**Comment by brennan** [comment]
@ldemay @TeresaNesteby Would you two be able to bump the version on a branch in this repo and make sure the CircleCi tests run so we know the major version bump is compatible with the current library's logic? Thanks!

**Comment by srthurman** [comment]
Closing in favor of: https://github.com/segment-integrations/analytics-android-integration-firebase/pull/8

**Comment by ldemay** [comment]
Please have a look at #9.
@brennan the repo is read-only, so the only way to PR for me is via fork.
It seems like I can't run your CI.
Thanks for your help!

**Pull request closed without merging**
