### PR TITLE
Added check on makeKey to replace dash from event-names

### PR DESCRIPTION
**Pull request by mcatta**
I have added a check to replace the dash with underscore inside `makeKey()` method to follow the documentation specs.

### CODE REVIEW

**Comment by slacabos** [comment]
@briemcnally @brennan can you guys have a look at this please?

**Comment by briemcnally** [comment]
@mcatta & @slacabos I am going to close this PR in favor of #30. I will be releasing that now to version 2.1.1. It should be available in Maven in a few hours.

**Comment by mcatta** [comment]
Hi @briemcnally , thank you for the support. I'm checking on https://mvnrepository.com/artifact/com.segment.analytics.android.integrations/firebase but the 2.1.1 is not still available, is it in pending? Thank you.
Marco

**Comment by briemcnally** [comment]
@mcatta I am looking into this today. Will provide an hopefully by this afternoon.

**Comment by briemcnally** [comment]
@mcatta Sorry about the delay. The version 2.1.1 have been posted to Maven: https://search.maven.org/artifact/com.segment.analytics.android.integrations/firebase/2.1.1/jar

**Comment by mcatta** [comment]
> @mcatta Sorry about the delay. The version 2.1.1 have been posted to Maven: https://search.maven.org/artifact/com.segment.analytics.android.integrations/firebase/2.1.1/jar

Don't worry, thank you very much!

**Pull request closed without merging**
