### PR TITLE
bump firebase to 16.0.1

### PR DESCRIPTION
**Pull request by srthurman**
Per request to bump version in a branch from this PR https://github.com/segment-integrations/analytics-android-integration-firebase/pull/7

### CODE REVIEW

**Comment by srthurman** [comment]
@brennan new PR using a branch here. Will followup offline about next steps.

@ldemay aside from this being the most up to date version of the library, are there specific changes that are included since 11.2.0 that you've found necessary to use the Segment <> Firebase Android destination?

**Comment by ldemay** [comment]
@srthurman `implementation 'com.segment.analytics.android.integrations:firebase:1.1.0'` prevents our project to use the last version of firebase as there is a dependency to an old version.
Nothing else!

**Comment by brennan** [comment]
@srthurman Would you please create a Change Control ticket and link it here so reviewers have context? Thanks!

**Comment by f2prateek** [comment]
could you update the PR description as well? It's a bit misleading currently. This is updating the firebase dependency AND migrating from v2 of the Android Gradle plugin to v3 and all the changes that come along with it (e.g. compile -> implementation).

I'd recommend these be separate PRs, especially in case there is a bug in one or the other and we need to revert.

**Comment by brennan** [comment]
@f2prateek @srthurman Closing this PR and opening two separate PRs per Prateek's request.

**Pull request closed without merging**
